config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments

  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end


  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments
    validates :title, presence: true, uniqueness: true#para Que el titulo no se repita uniqueness
    validates :body, presence: true, length: { minimum: 20 }
    before_save :set_visits_count

    def update_visits_count
      self.update(visits_count: self.visits_count + 1)
    end

    private

    def set_visits_count
      self.visits_count ||= 0
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_article, except: [:index, :new, :create]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article.update_visits_count
    @comment = Comment.new
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to @article
    else
       render :new
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Articulo Actualizado' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    redirect_to articles_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body,)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :doby)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% name ||= "Crear"%>
<h1> <%= name %> Articulo</h1>
<%= form_for(@article) do |f| %>

     <% @article.errors.full_messages.each do |message| %>
         <div class="be-blue white espacio">
            * <%= message %>
         </div>
     <%end%>

     <div class="field">
       <%= f.label :title %>
       <%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
     </div>
     <div class="field">
       <%= f.label :body %>
       <%= f.text_area :body, placeholder: "Escribe aqui el articulo",
                        style:"height:250px;", class:"form-control" %>
     </div>
     <div class="field">
         <%= f.submit "Guardar", class:"btn be-blue white"%>
     </div>
<%end%>

app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
       <%= render "form"%>
</div>

app/views/articles/index.html.erb
 <% @articles.each do |article| %>
     <h1><%= link_to article.title, article %></h1>

     <div>
         <p><%= article.body %> - <%= link_to "Eliminar", article, method: :delete, class:"red" %></p>
     </div>
 <%end%>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
 <%= render "form" %></div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<% unless @article.user.nil? %>
<p> Escrito Por: <%= @article.user.email %> </p>
<%end%>

<div> <p><%= @article.body %></p> </div>

<div class="field">
  <h3>Comentarios</h3>
  <%= render "comments/form"%>
  <ul id="comments-box">
   <% @article.comments.each do |comment| %>
      <li> <%= comment.body %> - <%= comment.user.email %> </li>
   <%end%>
  </ul>
</div>

<p> Visitas: <%= @article.visits_count %> </p>

<div>  <%= link_to "Editar", edit_article_path(@article)%> </div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :comment_user_id %>
  </div>

  <div class="field">
    <%= form.label :article_id %>
    <%= form.text_field :article_id, id: :comment_article_id %>
  </div>

  <div class="field">
    <%= form.label :doby %>
    <%= form.text_area :doby, id: :comment_doby %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Doby</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.doby %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Doby:</strong>
  <%= @comment.doby %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
     <%= render "partials/navigation" %>
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>
 

app/views/partials/_navigation.html.erb
 <header>
  <nav class="be-blue white large-padding">
      <ul class="no-list row center-xs menu">
         <li class="col-md pun">
             <h3 class="no-margin" id="logo">Blog XD</h3>
         </li>
          <li class="col-md pun">
              <%= link_to "Inicio", root_path %>
          </li>
          <li class="col-md pun">
              Programacion
          </li>
          <li class="col-md pun">
              Tecnologia
          </li>
          <li class="col-md pun">
              Diseño
          </li>
          <% if user_signed_in? %>
             <li class="col-md pun">
                 <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
             </li>
             <%else%>
             <li class="col-md pun">
                 <%= link_to "Iniciar Sesión", new_user_session_path %>
             </li>
             <li class="col-md pun">
                 <%= link_to "Crear Cuenta", new_user_registration_path %>
             </li>

          <%end%>
       </ul>
   </nav>
</header>

app/views/welcome/index.html.erb
<h1>Bienvenidos</h1>